name: tesla
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.8
  - pip
  - pip:
      - h5py==3.10.0
      - lpips==0.1.2
      - monai==1.3.0
      - numpy==1.23.5
      - packaging==21.3
      - Pillow==11.3.0
      - PyWavelets==1.1.1
      - PyYAML==6.0.2
      - scikit_image==0.16.2
      - tensorboardX==2.6.4
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.60.0
